language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - composer run-script phpunit
  - composer run-script phpcs
  - composer run-script build
